# Generated by Django 4.2.6 on 2023-10-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dpi', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('razon_visita', models.TextField(max_length=100)),
                ('receta', models.TextField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
