# Generated by Django 4.2.6 on 2023-11-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colegiado', models.IntegerField()),
                ('especialidad', models.CharField(max_length=30)),
                ('diagnostico', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=1),
        ),
    ]
