# Generated by Django 4.2.6 on 2023-11-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_paciente_nacimiento_alter_paciente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
