# Generated by Django 4.2.6 on 2023-11-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_paciente_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacimiento',
            field=models.CharField(max_length=10),
        ),
    ]
