# Generated by Django 4.2.6 on 2023-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='razon_visita',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='receta',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
