# Generated by Django 4.2.6 on 2023-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_customuser_diagnostico_alter_customuser_razon_visita_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
