# Generated by Django 4.2.6 on 2023-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='razon_visita',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='receta',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
