# Generated by Django 4.2.6 on 2023-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_remove_medico_diagnostico_paciente_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('fecha', models.CharField(max_length=10)),
                ('asunto', models.CharField(max_length=30)),
                ('contenido', models.TextField(max_length=300)),
            ],
        ),
    ]
