# Generated by Django 4.2.6 on 2023-11-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_visita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
