# Generated by Django 4.2.6 on 2023-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_paciente_fecha_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dpi', models.IntegerField()),
                ('fecha_visita', models.CharField(blank=True, max_length=10, null=True)),
                ('razon_visita', models.TextField(blank=True, max_length=100, null=True)),
                ('receta', models.TextField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=100, null=True)),
                ('doctor', models.CharField(max_length=30)),
            ],
        ),
    ]
