# Generated by Django 4.2.6 on 2023-11-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_rename_fecha_visita_historial_fecha_cita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dpi', models.IntegerField()),
                ('fecha_cita', models.CharField(max_length=10)),
                ('razon_cita', models.TextField(max_length=100)),
                ('receta', models.TextField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=100, null=True)),
                ('doctor', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
