# Generated by Django 4.2.6 on 2023-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_cita_delete_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_visita',
            new_name='fecha_cita',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='razon_visita',
            new_name='razon_cita',
        ),
    ]
